---
title: "Day1"
author: "Afsar Ali"
output:
  prettydoc::html_pretty:
    theme: Cayman
    highlight: github
    df_print: paged
    toc: yes
    toc_depth: '4'
---

```{r echo=TRUE}
# Course: Applied-Data-Analytics-EMSE-6767-D18
# Title: Day 2
# Purpose: Day 2 Draft
# Author: Afsar Ali
```
```{r echo=TRUE, message=FALSE, warning=FALSE}
# stddev.

data <- c(4, 2, 5, 1, 3, 6, 2, 4, 3, 5)

data.sum <- sum(data)
data.sq.sum <- sum(data * data)

data.var.manual <- (data.sq.sum - (data.sum^2)/length(data))/(length(data) - 1)
data.var <- var(x=data)

data.sd.manual <- sqrt(data.var.manual)
data.sd <- sd(data)

```
```{r echo=TRUE, message=FALSE, warning=FALSE}
# scatter.R
x = c(195,180,220,160,200,220,200,183,139,155)
y = c(130,128,138,122,140,148,142,127,116,123)

pearson_cor = cor(x, y)

data = data.frame(cbind(x,y))

cc <- coef(lm(x~y), data=data)
ggplot(data=data, aes(x=x, y=y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  ggtitle(paste("Pearson CF: ", format(pearson_cor,digits=2)))

```
```{r echo=TRUE, message=FALSE, warning=FALSE}

# relative_position_book.R

x = c(17,12,12,14,15,16,16,16,16,17,17,18,18,18,19,19,20, 20,20,20,20,20,20,20,
      21,21,21,22,22,23,23,23,24,24,25,26, 26,28,28,28)
#To concatenate resulting mean, standard deviation, variance, and coeficient of variation
c(mean(x), sd(x), var(x), 100*sd(x)/mean(x))
#To obtain quartiles including min and max
quantile(x)
#To obtain the range we find Max-Min
range(x)[2]-range(x)[1]
```
```{r echo=TRUE, message=FALSE, warning=FALSE}

# range.R

psi <- c(8538.24, 8450.16, 8494.27, 8317.34, 8443.99, 8368.04, 8368.94, 8424.41, 8427.34, 8517.64)

psi.range.manual <- max(psi) - min(psi)
psi.range <- diff(range(psi))
```
```{r echo=TRUE, message=FALSE, warning=FALSE}

# percentiles.R
salaries <- c(62, 48, 52, 63, 85, 51, 95, 76, 72, 51, 69, 73, 58, 55, 54)
salaries.sorted <- sort(salaries)

percentile.of.interest <- 70
quantile.of.interest <- 70.0/100.0
rank <- (length(salaries) + 1) * percentile.of.interest / 100
alpha <- rank - floor(rank)
percentile.manual <- salaries.sorted[floor(rank)] * (1 - alpha) + salaries.sorted[ceiling(rank)] * alpha

percentile <- quantile(x=salaries, probs=quantile.of.interest, type=6)

```
```{r echo=TRUE, message=FALSE, warning=FALSE}

# metrics_book.R
data = c(6, 8, 12, 9, 14, 18, 17, 23, 21, 23)
#To obtain summary statistics
summary(data)

#To obtain the mean, median, standard deviation, and variance
mean(data)
median(data)
sd(data)
var(data)

# To obtain the mode
names(table(data))[table(data) == max(table(data))]
```
```{r echo=TRUE, message=FALSE, warning=FALSE}
# lineplot.R
sales <- c(2, 1, 4, 10, 57, 62, 64, 68, 40, 15, 10, 5)
months <- 1:12

data <- data.frame(sales, months)
colnames(data) = c("Sales", "Months")

ggplot(data=data, aes(x=months, y=sales)) + geom_point(show.legend = TRUE) + geom_line() +ggtitle("Sales Per Month", subtitle = "LinePlot")

```

```{r echo=TRUE, message=FALSE, warning=FALSE}

# chebychev.R
data <- stats::rnorm(1000)

data.sd <- sd(data)
data.mean <- mean(data)

cheby <- function(k, data) {
  return (sum(data <= mean(data) + k * sd(data)) / length(data) * 100.0)
}
cheb <- sapply(2:10, cheby, data=data)
cheb.limits <- sapply(2:10,{function (i) (1-1/(i^2)) * 100})

cheb.data <- cbind(cheb, cheb.limits)
colnames(cheb.data) = c("Actual", "Chebyshev Bound")
View(cheb.data)

```


```{r echo=TRUE, message=FALSE, warning=FALSE}

# centrality.R
library(DescTools)  # Necessary for Mode

data <- c(8, 6, 9, 10, 8, 7, 11, 9, 8)
freq.data <- table(data)

mean.by.hand <- sum(data)/length(data)
median.by.hand <- sort(data)[floor(length(data)/2)]
mode.by.hand <- as.numeric(names(freq.data[max(freq.data)]))

centrality <- cbind(mean(data), median(data), Mode(x=data), mean.by.hand, median.by.hand, mode.by.hand)
colnames(centrality) = c("Mean", "Median", "Mode", "Mean.Manual", "Median.Manual", "Mode.Manual")

View(centrality)

```


```{r echo=TRUE, message=FALSE, warning=FALSE}

# boxplots.R

NoiseLevels = c(75,79,80,85,88,89,95,96,97,99,104,105,110,115,140)
#To plot boxplot
boxplot(NoiseLevels, main = 'Box plot of Noise Levels (dB)', ylab = 'Noise Levels (dB)', col ='grey')

boxplot(NoiseLevels, horizontal = TRUE, main = 'Box plot of Noise Levels (dB)', xlab = 'Noise Levels (dB)', col ='blue')

ggplot(data=data.frame(NoiseLevels),aes(x=NoiseLevels,y=0)) + geom_boxplot() + geom_jitter()
```





